### ISSUE TITLE
kmediatorrent not working (can't list movies/tv shows)

### ISSUE THREAD

**Issue by Johnneke** [jmarth/plugin.video.kmediatorrent#108]
Running Openelec 5.0.8 on a intel NUC

kodi.log:

14:00:13 T:140135714776832  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:13 T:140135714776832  NOTICE: Thread JobWorker start, auto delete: true
14:00:16 T:140135199385344  NOTICE: Previous line repeats 2 times.
14:00:16 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:16 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:16 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:16 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:16 T:140135199385344  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
14:00:16 T:140135199385344  NOTICE: [plugin.video.kmediatorrent] GA: Tracking /
14:00:16 T:140135190828800  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:19 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:19 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:19 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:19 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:19 T:140135199385344  NOTICE: [xbmcswift2] Request for "/tpb" matches rule for function "piratebay_index"
14:00:19 T:140135190828800  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:22 T:140135211448064  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:22 T:140135211448064  NOTICE: -->Python Interpreter Initialized<--
14:00:22 T:140135211448064 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:23 T:140135211448064 WARNING: Previous line repeats 26 times.
14:00:23 T:140135211448064  NOTICE: [xbmcswift2] Request for "/tpb/%2Fbrowse%2F205/0" matches rule for function "piratebay_page"
14:00:23 T:140135211448064  NOTICE: Traceback (most recent call last):
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
14:00:23 T:140135211448064  NOTICE:     plugin.run()
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
14:00:23 T:140135211448064  NOTICE:     items = self._dispatch(self.request.path)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 315, in _dispatch
14:00:23 T:140135211448064  NOTICE:     listitems = self.finish(listitems)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/xbmcmixin.py", line 493, in finish
14:00:23 T:140135211448064  NOTICE:     self.add_items(items)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/xbmcmixin.py", line 409, in add_items
14:00:23 T:140135211448064  NOTICE:     _items = [self._listitemify(item) for item in items]
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/library.py", line 155, in _fn
14:00:23 T:140135211448064  NOTICE:     items = fn(*a, **kwds)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
14:00:23 T:140135211448064  NOTICE:     items = list(items)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/tpb.py", line 75, in piratebay_page
14:00:23 T:140135211448064  NOTICE:     html_data = url_get(urljoin(BASE_URL, "%s/%d/7/100,200,500" % (root, page)), headers=HEADERS)
14:00:23 T:140135211448064  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
14:00:23 T:140135211448064  NOTICE:     with closing(urllib2.urlopen(req)) as response:
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 438, in error
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 438, in error
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
14:00:23 T:140135211448064  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
14:00:23 T:140135211448064  NOTICE: URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
14:00:23 T:140135211448064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 315, in _dispatch
                                                listitems = self.finish(listitems)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/xbmcmixin.py", line 493, in finish
                                                self.add_items(items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/xbmcmixin.py", line 409, in add_items
                                                _items = [self._listitemify(item) for item in items]
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/library.py", line 155, in _fn
                                                items = fn(*a, **kwds)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
                                                items = list(items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/tpb.py", line 75, in piratebay_page
                                                html_data = url_get(urljoin(BASE_URL, "%s/%d/7/100,200,500" % (root, page)), headers=HEADERS)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
                                                with closing(urllib2.urlopen(req)) as response:
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 438, in error
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 438, in error
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
                                            URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            -->End of Python script error report<--
14:00:23 T:140136528107392   ERROR: GetDirectory - Error getting plugin://plugin.video.kmediatorrent/tpb/%2Fbrowse%2F205/0
14:00:23 T:140136528107392   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kmediatorrent/tpb/%2Fbrowse%2F205/0) failed
14:00:23 T:140135211448064  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:23 T:140135211448064  NOTICE: -->Python Interpreter Initialized<--
14:00:23 T:140135211448064 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:24 T:140135211448064 WARNING: Previous line repeats 26 times.
14:00:24 T:140135211448064  NOTICE: [xbmcswift2] Request for "/tpb" matches rule for function "piratebay_index"
14:00:24 T:140135199385344  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:28 T:140135211448064  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:28 T:140135211448064  NOTICE: -->Python Interpreter Initialized<--
14:00:28 T:140135211448064 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:28 T:140135211448064 WARNING: Previous line repeats 26 times.
14:00:28 T:140135211448064  NOTICE: [xbmcswift2] Request for "/tpb/search" matches rule for function "piratebay_search"
14:00:35 T:140136528107392   ERROR: GetDirectory - Error getting plugin://plugin.video.kmediatorrent/tpb/search
14:00:35 T:140136528107392   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kmediatorrent/tpb/search) failed
14:00:35 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:35 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:35 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:35 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:35 T:140135199385344  NOTICE: [xbmcswift2] Request for "/tpb" matches rule for function "piratebay_index"
14:00:35 T:140135211448064  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:37 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:38 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:38 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:38 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:38 T:140135199385344  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
14:00:38 T:140135199385344  NOTICE: [plugin.video.kmediatorrent] GA: Tracking /
14:00:38 T:140135211448064  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:40 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:40 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:40 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:40 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:40 T:140135199385344  NOTICE: [xbmcswift2] Request for "/yify" matches rule for function "yify_index"
14:00:40 T:140135211448064  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:42 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:42 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:42 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:43 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:43 T:140135199385344  NOTICE: [xbmcswift2] Request for "/yify/browse/seeds/all/1" matches rule for function "yify_movies"
14:00:44 T:140135199385344  NOTICE: Traceback (most recent call last):
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
14:00:44 T:140135199385344  NOTICE:     plugin.run()
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
14:00:44 T:140135199385344  NOTICE:     items = self._dispatch(self.request.path)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
14:00:44 T:140135199385344  NOTICE:     listitems = view_func(**items)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/caching.py", line 52, in _fn
14:00:44 T:140135199385344  NOTICE:     ret = fn(*a, **kwds)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
14:00:44 T:140135199385344  NOTICE:     items = list(items)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/library.py", line 157, in _fn
14:00:44 T:140135199385344  NOTICE:     for item in items:
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/yify.py", line 94, in yify_show_data
14:00:44 T:140135199385344  NOTICE:     search_result = url_get_json("%s/api/list.json" % BASE_URL, params=args, headers=HEADERS)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 189, in url_get_json
14:00:44 T:140135199385344  NOTICE:     data = url_get(*args, **kwargs)
14:00:44 T:140135199385344  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
14:00:44 T:140135199385344  NOTICE:     with closing(urllib2.urlopen(req)) as response:
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1207, in http_open
14:00:44 T:140135199385344  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
14:00:44 T:140135199385344  NOTICE: URLError: <urlopen error [Errno -2] Name or service not known>
14:00:44 T:140135199385344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/caching.py", line 52, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
                                                items = list(items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/library.py", line 157, in _fn
                                                for item in items:
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/yify.py", line 94, in yify_show_data
                                                search_result = url_get_json("%s/api/list.json" % BASE_URL, params=args, headers=HEADERS)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 189, in url_get_json
                                                data = url_get(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
                                                with closing(urllib2.urlopen(req)) as response:
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1207, in http_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
14:00:44 T:140136528107392   ERROR: GetDirectory - Error getting plugin://plugin.video.kmediatorrent/yify/browse/seeds/all/1?limit=20&order=desc
14:00:44 T:140136528107392   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kmediatorrent/yify/browse/seeds/all/1?limit=20&order=desc) failed
14:00:44 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:44 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:44 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:44 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:44 T:140135199385344  NOTICE: [xbmcswift2] Request for "/yify" matches rule for function "yify_index"
14:00:44 T:140135211448064  NOTICE: Thread BackgroundLoader start, auto delete: false
14:00:46 T:140135199385344  NOTICE: Thread LanguageInvoker start, auto delete: false
14:00:47 T:140135199385344  NOTICE: -->Python Interpreter Initialized<--
14:00:47 T:140135199385344 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
14:00:47 T:140135199385344 WARNING: Previous line repeats 26 times.
14:00:47 T:140135199385344  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
14:00:47 T:140135199385344  NOTICE: [plugin.video.kmediatorrent] GA: Tracking /
14:00:47 T:140135211448064  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by Johnneke** [comment]
Solved the issue by removing Pulsar/Kmediatorrent/Xbmctorrent (also manually removed the folders on the storage partition for these addons) afterwards reinstalled the latest kmediatorrent and afterwards it was working.
